DROP TABLE IF EXISTS events;

CREATE TABLE events (
	id SERIAL PRIMARY KEY,
	name VARCHAR(30) NOT NULL DEFAULT 'UNNAMED EVENT',
	added TIMESTAMP NOT NULL DEFAULT NOW(),
	eventdate TIMESTAMP NOT NULL DEFAULT NOW(),
	image VARCHAR(2083) NOT NULL DEFAULT '/images/default.jpg'
);

SELECT * FROM events;